name: Azure Template Validation
on:
  workflow_dispatch: 
  push: 
    branches: 
    - main 
    - template-validation

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  template_validation_job:
    runs-on: ubuntu-latest
    name: Template validation

    steps:
      # Step 1: Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Validate the Azure template using microsoft/template-validation-action
      - name: Validate Azure Template
        uses: microsoft/template-validation-action@v0.4.3
        with:
          validateAzd: ${{ vars.AZD_VALIDATE }}
          useDevContainer: ${{ vars.AZD_USE_DEV_CONTAINER }}
          validateTests: ${{ vars.AZD_VALIDATE_TESTS }}
        id: validation
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
          AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Print the result of the validation
      - name: Print result
        run: cat ${{ steps.validation.outputs.resultFile }}