name: Test Workflow with Coverage

on:
  push:
    paths:
      - 'src/**/*.py'
      - '.flake8'
      - '.github/workflows/pylint.yml'

jobs:
  backend_tests:
    name: Backend Tests
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - uses: actions/checkout@v5  # Checkout the repository

      # Set up Python environment for Backend
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"  # Set Python version

      - name: Install Backend Dependencies
        run: |
          python -m pip install -r src/api/requirements.txt

      - name: Run Backend Tests with Coverage
        run: |
          if python -m pytest --cov=. --cov-report=xml --cov-report=html --cov-report=term-missing --junitxml=coverage-junit.xml ./src/tests; then
            echo "Tests completed, checking coverage."
            # Only fail if coverage does not meet criteria
            if [ -f coverage.xml ]; then
              COVERAGE=$(python -c "import xml.etree.ElementTree as ET; tree = ET.parse('coverage.xml'); root = tree.getroot(); coverage = root.find('coverage').get('lines').split('%')[0]; print(float(coverage))")
              if (( $(echo "$COVERAGE < 80" | bc -l) )); then
                echo "Coverage is below 80%, failing the job."
                exit 1
              fi
            fi
          else
            echo "No tests found, skipping coverage check."
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: |
            coverage.xml  # Correct path to backend coverage
            coverage-junit.xml  # Correct path to backend JUnit report
            htmlcov/  # Correct path to backend HTML coverage report